# Generated by Django 3.0.8 on 2020-07-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200726_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='politicalOrientation',
            field=models.IntegerField(null=True),
        ),
    ]
