# Generated by Django 3.0.8 on 2020-07-26 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200726_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='politicalOrientation',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
