# Generated by Django 3.0.8 on 2020-07-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200726_1529'),
        ('accounts', '0003_auto_20200730_1616'),
    ]

    operations = [
    ]
