# Generated by Django 3.0.6 on 2020-07-31 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20200730_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='politicalOrientation',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
