# Generated by Django 3.0.8 on 2020-07-26 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentToComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, upload_to='comment_photos')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='feed_photos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('referenceUrl', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmallFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='smallfeed_photos')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDislikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDislikeCTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.CommentToComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDislikeReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.ReferenceFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDislikeSmallFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smallFeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.SmallFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeCTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ctc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.CommentToComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.ReferenceFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLikeSmallFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smallFeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.SmallFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='PoliticanLikeLaw',
            new_name='PoliticanAgreeLaw',
        ),
        migrations.RenameModel(
            old_name='PoliticanDislikeLaw',
            new_name='PoliticanDisagreeLaw',
        ),
        migrations.RemoveField(
            model_name='law',
            name='comment_users',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='dislike_law',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='like_law',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='law',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Law'),
        ),
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, upload_to='comment_photos'),
        ),
        migrations.AddField(
            model_name='comment',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Politician'),
        ),
        migrations.AddField(
            model_name='politician',
            name='agree_law',
            field=models.ManyToManyField(blank=True, related_name='agree_politican', through='feedpage.PoliticanAgreeLaw', to='feedpage.Law'),
        ),
        migrations.AddField(
            model_name='politician',
            name='disagree_law',
            field=models.ManyToManyField(blank=True, related_name='disagree_politican', through='feedpage.PoliticanDisagreeLaw', to='feedpage.Law'),
        ),
        migrations.AddField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='evaluation',
            field=models.CharField(blank=True, choices=[('이행', 'implemented'), ('미흡', 'inadequate'), ('불이행', 'failure')], max_length=3),
        ),
        migrations.AlterField(
            model_name='law',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='politician',
            name='electedCount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='politician',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalParty',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=2),
        ),
        migrations.DeleteModel(
            name='UserCommentLaw',
        ),
        migrations.AddField(
            model_name='userlikecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.Comment'),
        ),
        migrations.AddField(
            model_name='userlikecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdislikecomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.Comment'),
        ),
        migrations.AddField(
            model_name='userdislikecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smallfeed',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='dislike_smallFeed', through='feedpage.UserDislikeSmallFeed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smallfeed',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_smallFeed', through='feedpage.UserLikeSmallFeed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencefeed',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='dislike_reference', through='feedpage.UserDislikeReference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencefeed',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_reference', through='feedpage.UserLikeReference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenttocomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.Comment'),
        ),
        migrations.AddField(
            model_name='commenttocomment',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='dislike_CTC', through='feedpage.UserDislikeCTC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenttocomment',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_CTC', through='feedpage.UserLikeCTC', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='dislike_comment', through='feedpage.UserDislikeComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_comment', through='feedpage.UserLikeComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='normalFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.NormalFeed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='smallFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.SmallFeed'),
        ),
    ]
