# Generated by Django 3.0.8 on 2020-07-26 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_auto_20200726_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='politicalOrientation',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalParty',
            field=models.CharField(choices=[('더', '더불어민주당'), ('미', '미래통합당'), ('정', '정의당'), ('국', '국민의당'), ('열', '열린민주당'), ('기', '기본소득당'), ('시', '시대전환'), ('무', '무소속')], max_length=2),
        ),
    ]
