# Generated by Django 3.0.8 on 2020-08-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_auto_20200803_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likeChoice',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], max_length=35),
        ),
    ]
