# Generated by Django 3.0.8 on 2020-07-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_auto_20200726_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalfeed',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Politician'),
        ),
        migrations.AlterField(
            model_name='normalfeed',
            name='title',
            field=models.CharField(choices=[('1', '개요'), ('2', '경력'), ('3', '과거 공약/이행률'), ('4', '발의 법률안'), ('5', '찬성/반대 법안'), ('6', '발언 및 논란')], max_length=256),
        ),
    ]
