# Generated by Django 3.0.6 on 2020-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='how',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='politician',
            name='district',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='politician',
            name='gender',
            field=models.CharField(choices=[('남', '남자'), ('여', '여자')], max_length=2),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalOrientation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalParty',
            field=models.CharField(choices=[('더불어민주당', '더불어민주당'), ('미래통합당', '미래통합당'), ('정의당', '정의당'), ('국민의당', '국민의당'), ('열린민주당', '열린민주당'), ('기본소득당', '기본소득당'), ('시대전환', '시대전환'), ('무소속', '무소속')], max_length=10),
        ),
    ]
