# Generated by Django 3.0.6 on 2020-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_auto_20200730_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalOrientation',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
