# Generated by Django 3.0.8 on 2020-07-30 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0004_auto_20200730_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallfeed',
            name='normalFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.NormalFeed'),
        ),
    ]
