# Generated by Django 3.0.8 on 2020-07-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_smallfeed_normalfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalfeed',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalFeeds', to='feedpage.Politician'),
        ),
        migrations.AlterField(
            model_name='smallfeed',
            name='normalFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smallFeeds', to='feedpage.NormalFeed'),
        ),
    ]
