# Generated by Django 3.0.6 on 2020-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_auto_20200730_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='politician',
            name='electedCount',
            field=models.CharField(blank=True, choices=[('남', '남자'), ('여', '여자')], max_length=10),
        ),
    ]
