# Generated by Django 3.0.8 on 2020-07-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_auto_20200730_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='photo',
            field=models.ImageField(blank=True, upload_to='politician_photos'),
        ),
    ]
