# Generated by Django 3.0.8 on 2020-07-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0007_auto_20200730_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeNormalFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smallFeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.NormalFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDislikeNormalFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('smallFeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedpage.NormalFeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='normalfeed',
            name='dislike_users',
            field=models.ManyToManyField(blank=True, related_name='dislike_normalFeed', through='feedpage.UserDislikeNormalFeed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalfeed',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_normalFeed', through='feedpage.UserLikeNormalFeed', to=settings.AUTH_USER_MODEL),
        ),
    ]
