# Generated by Django 3.0.8 on 2020-07-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0008_auto_20200730_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdislikenormalfeed',
            old_name='smallFeed',
            new_name='normalFeed',
        ),
        migrations.RenameField(
            model_name='userlikenormalfeed',
            old_name='smallFeed',
            new_name='normalFeed',
        ),
    ]
