# Generated by Django 3.0.8 on 2020-07-30 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0009_auto_20200730_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='normalFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedpage.NormalFeed'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='politician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedpage.Politician'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='smallFeed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedpage.SmallFeed'),
        ),
    ]
