# Generated by Django 3.0.8 on 2020-07-30 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0010_auto_20200730_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
        ),
        migrations.AlterField(
            model_name='comment',
            name='evaluation',
            field=models.CharField(blank=True, choices=[('이행', 'implemented'), ('미흡', 'inadequate'), ('불이행', 'failure')], max_length=35),
        ),
        migrations.AlterField(
            model_name='comment',
            name='law',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Law'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='normalFeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedpage.NormalFeed'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedpage.Politician'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='smallFeed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedpage.SmallFeed'),
        ),
    ]
