# Generated by Django 3.0.8 on 2020-07-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_auto_20200730_1814'),
        ('feedpage', '0011_auto_20200730_1812'),
    ]

    operations = [
    ]
