# Generated by Django 3.0.6 on 2020-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0013_auto_20200731_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='content',
        ),
        migrations.RemoveField(
            model_name='law',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='law',
            name='link',
        ),
        migrations.RemoveField(
            model_name='law',
            name='name',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='abstain_law',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='agree_law',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='disagree_law',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='propose_law',
        ),
        migrations.AddField(
            model_name='law',
            name='abstain_politican',
            field=models.ManyToManyField(blank=True, related_name='abstain_law', through='feedpage.PoliticanAbstainLaw', to='feedpage.Politician'),
        ),
        migrations.AddField(
            model_name='law',
            name='agree_politican',
            field=models.ManyToManyField(blank=True, related_name='agree_law', through='feedpage.PoliticanAgreeLaw', to='feedpage.Politician'),
        ),
        migrations.AddField(
            model_name='law',
            name='bill_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='law',
            name='committee',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='law',
            name='detail_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='law',
            name='disagree_politican',
            field=models.ManyToManyField(blank=True, related_name='disagree_law', through='feedpage.PoliticanDisagreeLaw', to='feedpage.Politician'),
        ),
        migrations.AddField(
            model_name='law',
            name='member_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='law',
            name='proposer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='law',
            name='proposer_etc',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='law',
            name='propse_dt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='PoliticanProposeLaw',
        ),
    ]
