# Generated by Django 3.0.8 on 2020-07-31 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0014_auto_20200731_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttocomment',
            name='created_at',
            field=models.CharField(default=django.utils.timezone.now, max_length=36),
        ),
    ]
