# Generated by Django 3.0.6 on 2020-08-01 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0014_auto_20200731_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='proposer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='feedpage.Politician'),
        ),
    ]
