# Generated by Django 3.0.6 on 2020-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0015_auto_20200801_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='politician',
            old_name='how',
            new_name='units',
        ),
        migrations.RemoveField(
            model_name='politician',
            name='name',
        ),
        migrations.AddField(
            model_name='politician',
            name='bth_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='bth_name',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='politician',
            name='e_mail',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='eng_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='hg_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='homepage',
            field=models.URLField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='politician',
            name='job_res_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='politician',
            name='tel_num',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='politician',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='politician',
            name='electedCount',
            field=models.CharField(blank=True, choices=[('초선', '초선'), ('재선', '재선'), ('3선', '3선'), ('4선', '4선'), ('5선', '5선'), ('6선', '6선'), ('7선', '7선'), ('8선', '8선'), ('9선', '9선'), ('10선', '10선')], max_length=10),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalCommittee',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='politician',
            name='politicalParty',
            field=models.CharField(blank=True, choices=[('더불어민주당', '더불어민주당'), ('미래통합당', '미래통합당'), ('정의당', '정의당'), ('국민의당', '국민의당'), ('열린민주당', '열린민주당'), ('기본소득당', '기본소득당'), ('시대전환', '시대전환'), ('무소속', '무소속')], max_length=10),
        ),
    ]
