# Generated by Django 3.0.8 on 2020-07-31 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0015_auto_20200731_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdislikectc',
            old_name='comment',
            new_name='ctc',
        ),
    ]
