# Generated by Django 3.0.8 on 2020-07-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0016_auto_20200731_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orientationvote',
            old_name='politican',
            new_name='politician',
        ),
    ]
