# Generated by Django 3.0.6 on 2020-08-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0018_auto_20200801_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='e_mail',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
