# Generated by Django 3.0.6 on 2020-08-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0019_auto_20200801_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='homepage',
            field=models.URLField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='tel_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
