# Generated by Django 3.0.6 on 2020-08-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0018_auto_20200801_1330'),
        ('feedpage', '0020_auto_20200801_1430'),
    ]

    operations = [
    ]
