# Generated by Django 3.0.8 on 2020-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0023_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttocomment',
            name='updated_at',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
